// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog post documents
 */
interface BlogPostDocumentData {
	/**
	 * Title field in *Blog post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Slug field in *Blog post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.slug
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	slug: prismic.KeyTextField;
	
	/**
	 * Description field in *Blog post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Cover field in *Blog post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.cover
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover: prismic.ImageField<never>;
	
	/**
	 * Content field in *Blog post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;

/**
 * Primary content in *Homepage → Slice zone → About Me → Primary*
 */
export interface IndexDocumentDataBodyHeroaboutSlicePrimary {
	/**
	 * Title field in *Homepage → Slice zone → About Me → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Hi, I'm ...
	 * - **API ID Path**: index.body[].heroabout.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * About field in *Homepage → Slice zone → About Me → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Hey, I like mac & cheese
	 * - **API ID Path**: index.body[].heroabout.primary.about
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	about: prismic.RichTextField;
	
	/**
	 * CTA Button Text field in *Homepage → Slice zone → About Me → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].heroabout.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	cta_button_text: prismic.RichTextField;
	
	/**
	 * CTA Button URL field in *Homepage → Slice zone → About Me → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].heroabout.primary.cta_button_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type IndexDocumentDataBodyHeroaboutSlice = prismic.Slice<"heroabout", Simplify<IndexDocumentDataBodyHeroaboutSlicePrimary>, never>

/**
 * Primary content in *Homepage → Slice zone → Projects → Primary*
 */
export interface IndexDocumentDataBodyProjectsSlicePrimary {
	/**
	 * Title field in *Homepage → Slice zone → Projects → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Ultimate Project
	 * - **API ID Path**: index.body[].projects.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Homepage → Slice zone → Projects → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: You want to add something?
	 * - **API ID Path**: index.body[].projects.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
}

/**
 * Item content in *Homepage → Slice zone → Projects → Items*
 */
export interface IndexDocumentDataBodyProjectsSliceItem {
	/**
	 * Project title field in *Homepage → Slice zone → Projects → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Turtle Finder
	 * - **API ID Path**: index.body[].projects.items.project_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	project_title: prismic.RichTextField;
	
	/**
	 * Project Type field in *Homepage → Slice zone → Projects → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Web Application
	 * - **API ID Path**: index.body[].projects.items.project_type
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	project_type: prismic.KeyTextField;
	
	/**
	 * Github Link field in *Homepage → Slice zone → Projects → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].projects.items.github_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	github_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Link field in *Homepage → Slice zone → Projects → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: http://turtlefinder.io
	 * - **API ID Path**: index.body[].projects.items.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Project Description field in *Homepage → Slice zone → Projects → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: I made this app for finding turtles near me
	 * - **API ID Path**: index.body[].projects.items.project_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	project_description: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type IndexDocumentDataBodyProjectsSlice = prismic.Slice<"projects", Simplify<IndexDocumentDataBodyProjectsSlicePrimary>, Simplify<IndexDocumentDataBodyProjectsSliceItem>>

/**
 * Primary content in *Homepage → Slice zone → Blog Posts → Primary*
 */
export interface IndexDocumentDataBodyBlogPostsSlicePrimary {
	/**
	 * Title field in *Homepage → Slice zone → Blog Posts → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Blog Posts about Cats
	 * - **API ID Path**: index.body[].blog_posts.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Homepage → Slice zone → Blog Posts → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Want to add something?
	 * - **API ID Path**: index.body[].blog_posts.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
}

/**
 * Item content in *Homepage → Slice zone → Blog Posts → Items*
 */
export interface IndexDocumentDataBodyBlogPostsSliceItem {
	/**
	 * Blog field in *Homepage → Slice zone → Blog Posts → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].blog_posts.items.blog
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	blog: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type IndexDocumentDataBodyBlogPostsSlice = prismic.Slice<"blog_posts", Simplify<IndexDocumentDataBodyBlogPostsSlicePrimary>, Simplify<IndexDocumentDataBodyBlogPostsSliceItem>>

/**
 * Item content in *Homepage → Slice zone → Contact → Items*
 */
export interface IndexDocumentDataBodyContactSliceItem {
	/**
	 * Contact Label field in *Homepage → Slice zone → Contact → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Twitter/GitHub/Email...
	 * - **API ID Path**: index.body[].contact.items.contact_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_label: prismic.KeyTextField;
	
	/**
	 * Contact Link field in *Homepage → Slice zone → Contact → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: https://github.com/xxx | mailto:myemail@email.com
	 * - **API ID Path**: index.body[].contact.items.contact_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type IndexDocumentDataBodyContactSlice = prismic.Slice<"contact", Record<string, never>, Simplify<IndexDocumentDataBodyContactSliceItem>>

/**
 * Primary content in *Homepage → Slice zone → Bio → Primary*
 */
export interface IndexDocumentDataBodyAboutMeSlicePrimary {
	/**
	 * Heading field in *Homepage → Slice zone → Bio → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].about_me.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Content field in *Homepage → Slice zone → Bio → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[].about_me.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type IndexDocumentDataBodyAboutMeSlice = prismic.Slice<"about_me", Simplify<IndexDocumentDataBodyAboutMeSlicePrimary>, never>

type IndexDocumentDataBodySlice = IndexDocumentDataBodyHeroaboutSlice | IndexDocumentDataBodyProjectsSlice | IndexDocumentDataBodyBlogPostsSlice | IndexDocumentDataBodyContactSlice | IndexDocumentDataBodyAboutMeSlice

/**
 * Content for Homepage documents
 */
interface IndexDocumentData {
	/**
	 * Slice zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<IndexDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

/**
 * Item in *Settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
	/**
	 * Platform field in *Settings → Socials*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].platform
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	platform: prismic.SelectField<"github" | "linkedin">;
	
	/**
	 * url field in *Settings → Socials*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Location field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
	
	/**
	 * Email field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Phone field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.phone
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone: prismic.KeyTextField;
	
	/**
	 * Socials field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

export type AllDocumentTypes = BlogPostDocument | IndexDocument | SettingsDocument;

/**
 * Primary content in *IndexHero → Default slice → Primary*
 */
export interface IndexHeroSliceDefaultSlicePrimary {
	/**
	 * Title field in *IndexHero → Default slice → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Your Nice title...
	 * - **API ID Path**: index_hero.default-slice.primary.Title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	Title: prismic.RichTextField;
	
	/**
	 * About field in *IndexHero → Default slice → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: I like turtles...
	 * - **API ID Path**: index_hero.default-slice.primary.About
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	About: prismic.RichTextField;
}

/**
 * Default slice variation for IndexHero Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: IndexHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndexHeroSliceDefaultSlice = prismic.SharedSliceVariation<"default-slice", Simplify<IndexHeroSliceDefaultSlicePrimary>, never>;

/**
 * Slice variation for *IndexHero*
 */
type IndexHeroSliceVariation = IndexHeroSliceDefaultSlice

/**
 * IndexHero Shared Slice
 *
 * - **API ID**: `index_hero`
 * - **Description**: IndexHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndexHeroSlice = prismic.SharedSlice<"index_hero", IndexHeroSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			BlogPostDocument,
			BlogPostDocumentData,
			IndexDocument,
			IndexDocumentData,
			IndexDocumentDataBodyHeroaboutSlicePrimary,
			IndexDocumentDataBodyProjectsSlicePrimary,
			IndexDocumentDataBodyProjectsSliceItem,
			IndexDocumentDataBodyBlogPostsSlicePrimary,
			IndexDocumentDataBodyBlogPostsSliceItem,
			IndexDocumentDataBodyContactSliceItem,
			IndexDocumentDataBodyAboutMeSlicePrimary,
			IndexDocumentDataBodySlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSocialsItem,
			AllDocumentTypes,
			IndexHeroSlice,
			IndexHeroSliceDefaultSlicePrimary,
			IndexHeroSliceVariation,
			IndexHeroSliceDefaultSlice
		}
	}
}